callbacks:
  list:
  - earlystop
  metrics:
  - val_loss
  - val_roc
  - train_loss
  mode: max
  monitor: val_roc
  patience: 300
  write_grads: false
data:
  T_max: 1000.0
  T_min_warn: 30
  T_warning: 5
  augment_during_training: false
  augmentation_mode: none
  bleed_in: 0
  bleed_in_remove_from_test: true
  current_end_thresh: 10000
  current_index: 0
  current_thresh: 750000
  cut_shot_ends: false
  dt: 0.001
  equalize_classes: false
  floatx: float32
  normalizer: var
  plotting: false
  positive_example_penalty: 1.0
  recompute: false
  recompute_normalization: false
  signal_to_augment: None
  use_shots: 200000
  window_decay: 2
  window_size: 10
env:
  name: torch-env
  type: anaconda3
fs_path: /tigress
model:
  PCS: true
  backend: tensorflow
  cell_order: 2
  cell_rank: 3
  cell_steps: 6
  clipnorm: 10.0
  dense_regularization: 0.01
  dense_size: 160
  dropout_prob: 0.05
  ignore_timesteps: 100
  kernel_size_temporal: 9
  length: 300
  loss_scale_factor: 1
  lr: 0.001982435726325936
  lr_decay: 1.0
  lr_decay_factor: 1.2
  lr_decay_patience: 10
  model_type: LSTM
  num_conv_filters: 5
  num_conv_layers: 3
  optimizer: adam
  pool_size: 2
  pred_batch_size: 64
  pred_length: 300
  regularization: 0.0
  return_sequences: true
  rnn_layers: 3
  rnn_size: 50
  rnn_type: LSTM
  shallow: false
  shallow_model:
    C: 1.0
    kernel: rbf
    learning_rate: 0.1
    max_depth: 3
    n_estimators: 100
    num_samples: 1000000
    scale_pos_weight: 10.0
    skip_train: false
    type: xgboost
  simple_conv: true
  size_conv_filters: 3
  skip: 1
  stateful: true
  tcn_hidden: 15
  tcn_layers: 8
  torch: true
  tt_lstm_hidden: 10
  warmup_steps: 0
num_gpus: 1
paths:
  data: d3d_data_0D
  executable: torch_learn.py
  shallow_executable: learn.py
  shot_list_dir: /shot_lists/
  signal_prepath: /signal_data/
  specific_signals: []
  tensorboard_save_path: /Graph/
target: ttdinv
training:
  as_array_of_shots: true
  batch_generator_warmup_steps: 0
  batch_size: 128
  data_parallel: false
  hyperparam_tuning: true
  max_patch_length: 100000
  num_batches_minimum: 200
  num_epochs: 1000
  num_shots_at_once: 200
  ranking_difficulty_fac: 1.0
  shuffle_training: true
  train_frac: 0.75
  use_mock_data: false
  validation_frac: 0.33
